version: '3.4'

services:
  # SOURCE DB
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/retail_metabase.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
    ports:
      - ${SOURCE_DB_PORT}:3306
    environment:
      # MYSQL_DATABASE: ${SOURCE_DB_DATABASE}
      MYSQL_USER: ${SOURCE_DB_USER}
      MYSQL_PASSWORD: ${SOURCE_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SOURCE_DB_ROOT_PASSWORD}
    command: ['--default-authentication-plugin=mysql_native_password']


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: ${PHPMYADMIN_PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${PHPMYADMIN_MYSQL_ROOT_PASSWORD}
      PMA_PORT: ${PHPMYADMIN_PMA_PORT}
  
  # BUISENSS ANALYTICAL TOOL
  metabase:
    image: metabase/metabase:latest
    restart: always
    ports:
      - ${METABSE_PORT}:3000
    depends_on:
      - mysql
    environment:
      MB_DB_TYPE: ${METABASE_DB_TYPE}
      MB_DB_DBNAME: ${METABASE_DB_DBNAME}
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: ${SOURCE_DB_ROOT_PASSWORD}
      MB_DB_HOST: mysql
    # networks:
    #   - app-network
    #   - app2-network

#   metabase-mysql:
#     image: mysql:latest
#     restart: always
#     environment:
#       MYSQL_DATABASE: ${METABASE_DB_DBNAME}
#       MYSQL_USER: ${METABASE_DB_USER}
#       MYSQL_PASSWORD: ${METABASE_DB_PASSWORD}
#       MYSQL_ROOT_PASSWORD: ${SOURCE_DB_ROOT_PASSWORD}
#     ports:
#       - 3307:3306
#     volumes:
#       - ./metabase/metabase.sql:/docker-entrypoint-initdb.d/init.sql
#       - ./metabase/metabase-db:/var/lib/mysql
#     networks:
#       - app2-network
#     command: ['--default-authentication-plugin=mysql_native_password']

# #Docker Networks
# networks:
#   app-network:
#   app2-network:
#     driver: bridge

